apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    db: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongo-secret
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mongo-secret
          image: mongo
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: mongo
  name: mongo-service
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    db: mongo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  database_url: mongo-service
  database_port: "27017"
